;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Game
DestinationPath=Content/Localization/Game
ManifestName=Game.manifest
ArchiveName=Game.archive
PortableObjectName=Game.po
ResourceName=Game.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateDialogueWaveParameters=true
NativeCulture=ru
CulturesToGenerate=ru
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=Source
SearchDirectoryPaths=Config
ExcludePathFilters=Source/*/Intermediate/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/ThirdParty/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=InternationalizationExport
bExportLoc=true
bImportLoc=false

[GatherTextStep5]
CommandletClass=GenerateTextLocalizationResource

